### ISSUE TITLE
Lectura de datos por puerto Serial

### ISSUE THREAD

**Issue by IngJuanZD** [IngJuanZD/Arduino-Python-Serial#1]
Al momento de leer los dato del puerto serie enviados desde Arduino, no logro interpretar los datos para poder compáralos con un `if (dato=='F')` o alguna otra función y realizar una acción

**Comment by ramun9533** [comment]
Noto que no usas librerías.
Sugiero que cambies de motor por un servomotor o si gustas de más precisión un motor paso a paso (para estos tipos de electromecánicos hay librerías) . En caso de no haya presupuesto, sugiero colocar switch límite donde deses que se detenga el motor.

**Comment by IngJuanZD** [comment]
> Noto que no usas librerías.
> Sugiero que cambies de motor por un servomotor o si gustas de más precisión un motor paso a paso (para estos tipos de electromecánicos hay librerías). En caso de no haya presupuesto, sugiero colocar switch límite donde deses que se detenga el motor.

Gracias, es un proyecto es  personal y por el momento no cuento con presupuesto alguno , la idea es replicar esto a súper bajo costo.
https://orangemonkie.com/product/foldio360-3/

**Comment by IngJuanZD** [comment]
Se corrige la forma de tomar el dato del puerto serial usando solo read() y se decodifica como [ascii] para usar el valor como un String
